addr: 127.0.0.1:6379
password: ""
poolsize: 10
xaxretry: 3
idletimeout: 5
minidleconns: 5
tickertime: 60
delaybucket: 5
reversedbucket: 5
MaxTries: 5
port: ":9091"
serveerrorlog: "../serve_logs/error.log"
serveinfolog: "../serve_logs/access.log"
clienterrorlog: "../client_logs/error.log"
clientinfolog: "../client_logs/access.log"